services:
  - docker

install:
  - docker pull mkaczanowski/packer-builder-arm
script:
  - docker run --rm --privileged -v /dev:/dev -v ${PWD}:/build mkaczanowski/packer-builder-arm build boards/raspberry-pi/raspbian.json

deploy:
  # The following block is responsible to upload the zip files
  - provider: releases
    skip-cleanup: true
    api_key: $GITHUB_TOKEN
    file:
      - "raspberry-pi.img"

    on:
      # Create GitHub Releases for new git tags
      # regardless of the branch.
      all_branches: true
      tags: true
