services:
  - docker

install:
  - docker pull mkaczanowski/packer-builder-arm
script:
  - docker run --rm --privileged -v /dev:/dev -v ${PWD}:/build mkaczanowski/packer-builder-arm build raspbian.json

before_deploy:
  - echo ALL G

deploy:
  - provider: releases
    skip-cleanup: true
    api_key: $GITHUB_TOKEN
    file:
      - "raspberry-pi.img"

    on:
      # Create GitHub Releases for new git tags
      # regardless of the branch.
      all_branches: true
      tags: true
